# Generated by Django 4.1 on 2024-02-02 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_user_is_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_id',
            field=models.CharField(default='3303adb8-56b0-4b0c-b74c-5b5eea66881f', max_length=128, unique=True),
        ),
    ]
